#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-sphinx_notfound_page
Version  : 1.0.0
Release  : 13
URL      : https://files.pythonhosted.org/packages/57/21/fa33931d3c94eccaebe3ef26f0460b3aab5fe3767b996f28057ac730af95/sphinx_notfound_page-1.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/57/21/fa33931d3c94eccaebe3ef26f0460b3aab5fe3767b996f28057ac730af95/sphinx_notfound_page-1.0.0.tar.gz
Summary  : Sphinx extension to build a 404 page with absolute URLs
Group    : Development/Tools
License  : MIT
Requires: pypi-sphinx_notfound_page-license = %{version}-%{release}
Requires: pypi-sphinx_notfound_page-python = %{version}-%{release}
Requires: pypi-sphinx_notfound_page-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(flit_core)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
|Build| |PyPI version| |Docs badge| |License|
sphinx-notfound-page
====================

%package license
Summary: license components for the pypi-sphinx_notfound_page package.
Group: Default

%description license
license components for the pypi-sphinx_notfound_page package.


%package python
Summary: python components for the pypi-sphinx_notfound_page package.
Group: Default
Requires: pypi-sphinx_notfound_page-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinx_notfound_page package.


%package python3
Summary: python3 components for the pypi-sphinx_notfound_page package.
Group: Default
Requires: python3-core
Provides: pypi(sphinx_notfound_page)
Requires: pypi(sphinx)

%description python3
python3 components for the pypi-sphinx_notfound_page package.


%prep
%setup -q -n sphinx_notfound_page-1.0.0
cd %{_builddir}/sphinx_notfound_page-1.0.0
pushd ..
cp -a sphinx_notfound_page-1.0.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1693410016
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sphinx_notfound_page
cp %{_builddir}/sphinx_notfound_page-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sphinx_notfound_page/b99b217a3ed7d3106b05bf2587e781909c1595b3 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sphinx_notfound_page/b99b217a3ed7d3106b05bf2587e781909c1595b3

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
